---

- name: Creating sandboxes.
  debug: msg='WARNING! This will take a long time (about 30min per VM)'

- name: Download & mound iso's
  include: iso.yml

- name: Generate windows VMs
  include: winvm_create.yml

- name: Snapshot windows VMs
  include: winvm_snapshot.yml
