---
# Here we take a snapshot of the vm and publish it to cuckoo
- name: Fill vm's with dependencies
  command: "vmcloak install {{ machines[item].VMCloack.template_name }} {{ machines[item].VMCloack.dependencies }}"
  become_user: cuckoo
  become: true
  with_items: "{{machines}}"
  when: machines[item].VMCloack is defined
