#!/usr/bin/env ansible-playbook
---
- name: Install cuckoo
  hosts: vmware
  become: true

  roles:
    - virtualbox
    - geerlingguy.elasticsearch
    - cuckoo
    - cuckoo_conf
    # - inetsim
    - web
