#!/usr/bin/env ansible-playbook
---
- name: Install cuckoo
  hosts: esxi
  become: true

  roles:
    - virtualbox
    - geerlingguy.elasticsearch
    - cuckoo
    - inetsim
    - cuckoo_conf
    - web
