#!/bin/sh
### BEGIN INIT INFO
# Provides:          StartVM
# Required-Start:    $network $remote_fs $named
# Required-Stop:     $network $remote_fs $named
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Description:       Start virtualBox machines and vboxnet0
### END INIT INFO

#Edit these variables!
VMUSER=cuckoo
VMNAME="inetsim"
IPADDR="192.168.56.1"
NETMASK="255.255.255.0"

start() {
  echo "Starting VirtualBox VM..."
  sudo vmcloak-vboxnet0
  sudo -H -b -u $VMUSER /usr/bin/VBoxHeadless -s "$VMNAME"
  # sudo -H -b -u $VMUSER bash -c "cd /home/cuckoo/inetsime && vagrant up"
}

stop() {
  echo "Saving state of Virtualbox VM..."
  sudo -H -u  $VMUSER /usr/bin/VBoxManage controlvm "$VMNAME" poweroff
  # sudo -H -u $VMUSER bash -c "cd /home/cuckoo/inetsime && vagrant down"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
