---
cuckoo_git_version: "2.0.0"
yara_git_version: "v3.5.0"
volatility_git_version: "2.6"

apt_requirements:
    - git
    - curl
    - python-django
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - python-pip
    - python-dev
    - libfuzzy-dev
    - tcpdump
    - libcap2-bin
    - wget
    - dnsmasq
    - python
    - mongodb
    - python-bson
    - libmagic-dev
    - build-essential
    - libreadline-gplv2-dev
    - libjpeg8-dev
    - zlib1g
    - zlib1g-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
    - libfreetype6-dev
    - libtool
    - automake
    - make
    - gcc
    - libjansson-dev
    - libfuzzy-dev
    - libffi-dev
    - python-magic
    - python-gridfs
    - python-libvirt
    - supervisor
    - genisoimage
    - flex

pip_requirements:
    - django
    - django-ratelimit
    - dnspython
    - jinja2
    - sqlalchemy==0.9.9
    - pymongo
    - bottle
    - pefile
    - chardet
    - pydeep
    - pygal
    - vmcloak
    - distorm3
    - nose
    - gunicorn
    - dpkt
    - yara-python

conf_files:
   - cuckoo.conf
   - memory.conf
   - virtualbox.conf
   - reporting.conf
   - winxp3.conf
