---
apt_requirements:
    - git
    - curl
    - python-django
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - python-pip
    - python-dev
    - libfuzzy-dev
    - tcpdump
    - apparmor-utils
    - libcap2-bin
    - wget
    - dnsmasq
    - python
    - mongodb
    - python-bson
    - libmagic-dev
    - build-essential
    - libreadline-gplv2-dev
    - libjpeg-dev
    - zlib1g
    - zlib1g-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
    - libfreetype6-dev
    - libtool
    - automake
    - make
    - gcc
    - libjansson-dev
    - libfuzzy-dev
    - libffi-dev
    - python-magic
    - python-gridfs
    - python-libvirt
    - supervisor
    - genisoimage
    - flex
    - bison
    - python-virtualenv
    - python-setuptools
    - swig
    - postgresql
    - pcregrep
    - vagrant
    - mysql-server
    - python-mysqldb
    - htop
    - nload
    - links
    - tree

pip_requirements:
    - pip
    - setuptools
    - django
    - django-ratelimit
    - dnspython
    - jinja2
    - sqlalchemy==1.0.8
    - pymongo
    - bottle
    - pefile
    - chardet
    - pydeep
    - pygal
    - vmcloak
    - distorm3
    - nose
    - gunicorn
    - dpkt
    - yara-python
    - uwsgi
    - pycrypto
    - OpenPyxl
    - ujson
    - pillow

conf_files:
   - cuckoo.conf
   - memory.conf
   - virtualbox.conf
   - reporting.conf
