---
- name: Copy cuckoo.conf config file
  template: src=templates/cuckoo.conf.j2 dest={{ conf_dir }}cuckoo.conf

- name: Copy memory.conf config file
  template: src=templates/memory.conf.j2 dest={{ conf_dir }}memory.conf

- name: Copy processing.conf config file
  template: src=templates/processing.conf.j2 dest={{ conf_dir }}processing.conf

- name: Copy reporting.conf config file
  template: src=templates/reporting.conf.j2 dest={{ conf_dir }}reporting.conf

- name: Copy virtualbox.conf config file
  template: src=templates/virtualbox.conf.j2 dest={{ conf_dir }}virtualbox.conf

- name: Copy winxp3.conf config file
  template: src=templates/winxp3.conf.j2 dest={{ conf_dir }}winxp3.conf
