---
- name: update & upgrade apt
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Configure the Oracle APT key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc state=present

- name: Configure the VirtualBox Debian or Ubuntu APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install VirtualBox
  apt:
    pkg: virtualbox-{{ virtualbox_version }}
    state: present
    update_cache: yes
  ignore_errors: yes # can still be running if we just update, ignore error then.

- name: Get virtualbox_version
  command: bash -l -c "VBoxManage --version | sed -r 's/([0-9])\.([0-9])\.([0-9]{1,2})r([0-9]+).*/\1.\2.\3\/Oracle_VM_VirtualBox_Extension_Pack-\1.\2.\3-\4.vbox-extpack/'"
  register: vbox_extpack

- name: Download Virtualbox extpack
  get_url:
    url: http://download.virtualbox.org/virtualbox/{{ vbox_extpack.stdout }}
    dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
    mode: 0644

- name: Install Virtualbox extpack
  command: bash -l -c "echo y | vboxmanage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack"
  become: true
  args:
    creates: /usr/lib/virtualbox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack
