---
- name: Install requirements from apt
  apt: pkg={{ item }} state=latest
  with_items: apt_requirements
  become: true

- name: Install requirements from pip
  pip: name={{ item }}
  with_items: pip_requirements
  become: true

- name: give tcpdump root permissions
  command: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
  become: true

- name: Download yara git {{yara_git_version}}
  git:
    repo: 'https://github.com/VirusTotal/yara.git'
    dest: /tmp/yara
    version: "{{yara_git_version}}"
  become: true

- name: Download volatility git {{volatility_git_version}}
  git:
    repo: 'https://github.com/volatilityfoundation/volatility.git'
    dest: /tmp/volatility
    version: "{{volatility_git_version}}"
  become: true

- name: Install volatility
  command: python setup.py install
  args:
    chdir: /tmp/volatility
  become: true

- name: Compile & install yara
  become: true
  shell: >
    cd /tmp/yara ;
    ./bootstrap.sh ;
    ./configure --enable-cuckoo --enable-magic ;
    make install ;
  args:
    chdir: /tmp/yara

- name: Create cuckoo group
  group: name=cuckoo
  become: true

- name: Create cuckoo user
  user:
    name: cuckoo
    groups: cuckoo,vboxusers,sudo
    shell: /bin/bash
    password: $6$igzTj8a5LV0$OP9/fAIXmVr2/qPjDJLZ5DYx0F7maMZ7QT99ee2KbkfqAWNC3uVCrGohDpk5cUmfnm8t4qIOuhnlw6FuKP4sL0 # generate pw using mkpasswd --method=sha-512
  become: true

- name: Sudo group with no passwd
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"

- name: Check if cuckoo is installed
  stat: path=/home/cuckoo/cuckoo/
  register: foo_stat

- name: Print FOO
  debug:
    msg: "{{foo_stat}}"

- name: Download cuckoo {{cuckoo_git_version}}
  git:
    repo: 'https://github.com/cuckoosandbox/cuckoo.git'
    dest: /home/cuckoo/cuckoo/
    version: "{{cuckoo_git_version}}"
  become: true
  when: foo_stat.stat.exists == False

- name: Set cuckoo permissions
  file:
    path: /home/cuckoo/cuckoo/
    owner: cuckoo
    group: cuckoo
    mode: 0644
    state: directory
    recurse: yes
  when: foo_stat.stat.exists == False
  become: true

- name: Copy cuckoo configuration
  copy: src={{ item }} dest=/home/cuckoo/cuckoo/conf/{{ item }} owner=cuckoo group=cuckoo mode=0644
  with_items: conf_files

# - name: Copy cuckoo start script to /usr/local/bin
#   copy: src=cuckoo dest=/usr/local/bin/ owner=root group=root mode=0755
#
