---
- name: Install requirements from apt
  apt: pkg={{ item }} state=latest
  with_items: "{{apt_requirements}}"
  become: true

- name: Install requirements from pip
  pip:
    name: "{{ item }}"
    state: latest # pip install --upgrade equivalent
  with_items: "{{pip_requirements}}"
  become: true

- name: give tcpdump root permissions
  command: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
  become: true

- name: tcpdump apparmor disable on Ubuntu
  command: sudo aa-disable /usr/sbin/tcpdump
  ignore_errors: yes
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Download yara git {{yara_git_version}}
  git:
    repo: 'https://github.com/VirusTotal/yara.git'
    dest: /tmp/yara
    version: "{{yara_git_version}}"
    update: no
  become: true

- name: Compile & install yara
  become: true
  shell: >
    cd /tmp/yara ;
    ./bootstrap.sh ;
    ./configure --enable-cuckoo --enable-magic ;
    make install ;
  args:
    chdir: /tmp/yara

- name: Download volatility git {{volatility_git_version}}
  git:
    repo: 'https://github.com/volatilityfoundation/volatility.git'
    dest: /tmp/volatility
    version: "{{volatility_git_version}}"
    update: no
  become: true

- name: Install volatility
  command: python setup.py install
  args:
    chdir: /tmp/volatility
  become: true

- name: Create cuckoo group
  group: name=cuckoo
  become: true

- name: Create cuckoo user
  user:
    name: cuckoo
    groups: cuckoo,vboxusers,sudo
    shell: /bin/bash
    password: $6$igzTj8a5LV0$OP9/fAIXmVr2/qPjDJLZ5DYx0F7maMZ7QT99ee2KbkfqAWNC3uVCrGohDpk5cUmfnm8t4qIOuhnlw6FuKP4sL0 # = cuckoo | generate pw using mkpasswd --method=sha-512
  become: true

- name: Sudo group with no passwd
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"

- name: Install setuptools for pip
  pip: name=setuptools
  become: true

- name: Install cuckoo from pip
  pip:
    name: cuckoo
    version: "{{cuckoo_version}}"
  become: true
  when: cuckoo_install_method == "pip"

- name: Create vboxnet0
  shell: >
    VBoxManage hostonlyif create ;
    VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1 --netmask 255.255.255.0
  become: true

  # this Initializes cuckoo to the cuckoo homedir
- name: Initialize cuckoo (non-virtualenv)
  shell: >
     cuckoo
  args:
    chdir: /home/cuckoo/
    creates: /home/cuckoo/.cuckoo/
  become_user: cuckoo
  become_method: sudo

- name: Download cuckoo community signatures (non-virtualenv)
  shell: >
     cuckoo community
  args:
    chdir: /home/cuckoo/
    creates: /home/cuckoo/.cuckoo/
  become_user: cuckoo
  become_method: sudo
