---
- name: Configure the Vagrant APT key
  apt_key:
    keyserver: pgp.mit.edu
    id: AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4

- name: Configure the Vagrant Debian or Ubuntu APT repositories
  apt_repository: repo="deb http://vagrant-deb.linestarve.com/ any main" state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: Install requirements from apt
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: "{{apt_requirements}}"
  become: true

- name: Install requirements from pip
  pip:
    name: "{{ item }}"
    state: latest # pip install --upgrade equivalent
  with_items: "{{pip_requirements}}"
  become: true

- name: Create a new database with name 'cuckoo'
  mysql_db:
    name: cuckoo
    state: present

- mysql_user:
    name: cuckoo
    password: cuckoo
    priv: '*.*:ALL'
    state: present

- name: give tcpdump root permissions
  command: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
  become: true

- name: tcpdump apparmor disable on Ubuntu
  command: aa-disable /usr/sbin/tcpdump
  ignore_errors: yes
  when: ansible_distribution == 'Ubuntu'
  become: true

- shell: yara -v
  register: yara
  ignore_errors: yes

- name: Download yara git {{yara_git_version}}
  git:
    repo: 'https://github.com/VirusTotal/yara.git'
    dest: /tmp/yara
    version: "v{{yara_git_version}}"
    update: no
  become: true
  when: 'yara_git_version|string not in yara.stdout'

- name: Compile & install yara
  become: true
  shell: >
    cd /tmp/yara ;
    ./bootstrap.sh ;
    ./configure --enable-cuckoo --enable-magic ;
    make install ;
  args:
    chdir: /tmp/yara
  when: 'yara_git_version|string not in yara.stdout'

- name: Download volatility git {{volatility_git_version}}
  git:
    repo: 'https://github.com/volatilityfoundation/volatility.git'
    dest: /tmp/volatility
    version: "{{volatility_git_version}}"
    update: no
  become: true


- name: Install volatility
  command: python setup.py   install
  args:
    chdir: /tmp/volatility
  become: true

- name: Create cuckoo group
  group: name=cuckoo
  become: true

- name: Create cuckoo user
  user:
    name: cuckoo
    groups: cuckoo,vboxusers,sudo
    shell: /bin/bash
    password: $6$vt76gQ9hf$RJo2Qp3iGKBdcV5wfjTwpDSCVmZMxZQvfEmhEUpyJNXHtTvYRSVy8Mdu7G9G/X0g/FhwC3KiMld/dvj/GnRft/ # = cuckoo_kRAYe93n | generate pw using mkpasswd --method=sha-512
  become: true

- name: Sudo group with no passwd
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"

- name: Install setuptools for pip
  pip: name=setuptools
  become: true

- name: Install cuckoo from pip
  pip:
    name: cuckoo
    version: "{{cuckoo_version}}"
  become: true
  when: cuckoo_install_method == "pip"

- name: Create vboxnet0
  shell: >
    VBoxManage hostonlyif create ;
    VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1 --netmask 255.255.255.0
  become: true

  # this Initializes cuckoo to the cuckoo homedir
- name: Initialize cuckoo (non-virtualenv)
  shell: >
     cuckoo
  args:
    chdir: /home/cuckoo/
    creates: /home/cuckoo/.cuckoo/
  become_user: cuckoo
  become_method: sudo

- name: Download cuckoo community signatures (non-virtualenv)
  shell: >
     cuckoo community
  args:
    chdir: /home/cuckoo/
    creates: /home/cuckoo/.cuckoo/signatures/compat.py
  become_user: cuckoo
  become_method: sudo

- name: Create rooter log directory
  file: path="/var/log/cuckoo/" state=directory
  become: true

- name: Copy supervisord cuckoo rooter configuration file
  copy: src=supervisord-cuckoo-rooter.conf dest=/etc/supervisor/conf.d/ owner=root group=root mode=0755
  become: true

- name: Create rooter log directory
  file: path="/var/log/cuckoo/" state=directory
  become: true

- name: Copy supervisord cuckoo service configuration file
  copy: src=supervisord-cuckoo-service.conf dest=/etc/supervisor/conf.d/ owner=root group=root mode=0755
  become: true
  notify:
    - start supervisord
    - restart supervisord

- name: remove windows line-endings
  local_action: replace dest={{playbook_dir}}/roles/cuckoo/files/cuckoo-update regexp="\r"

- name: Copy cuckoo-update file
  copy: src=cuckoo-update dest=/usr/bin/ owner=root group=root mode=a+x
  become: true

- cron:
    name: "Update cuckoo signatures"
    minute: "0"
    hour: "2"
    job: "/usr/bin/cuckoo-update"
