---
- name: Configure the tor APT key
  apt_key:
    keyserver: keys.gnupg.net
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89

- name: Add tor apt repo
  apt_repository:
    repo: "deb http://deb.torproject.org/torproject.org/ {{ ansible_lsb.codename }} main"
    update_cache: yes


- name: Install tor apt package
  apt:
    pkg:
      - tor
      - deb.torproject.org-keyring
    state: latest

- name: Edit tor config
  blockinfile:
    path: /etc/tor/torrc
    block: |
      TransPort 192.168.56.1:9040
      DNSPort 192.168.56.1:5353

- name: Restart tor
  become: true
  shell: >
    /etc/init.d/tor restart

- name: Copy tor supervisord configuration file
  copy: src=supervisor-tor.conf dest=/etc/supervisor/conf.d/ owner=root group=root mode=0755
  become: true
