---

- name: Add nginx apt key
  apt_key:
    url: 'http://nginx.org/keys/nginx_signing.key'

- name: Add nginx apt repo
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_lsb.id|lower }}/ {{ ansible_lsb.codename }} nginx"
    update_cache: yes

- name: Install Nginx apt package
  apt:
    pkg: nginx
    state: latest

- name: Disable default servers
  file:
    path: /etc/nginx/conf.d/{{ item.path }}
    state: absent
  with_items:
    - { path: 'default.conf' }
    - { path: 'example_ssl.conf' }

- name: Copy nginx configuration file
  copy: src=cuckoo_web.conf dest=/etc/nginx/sites-available/ owner=www-data group=www-data mode=0755
  become: true

- name: Enable nginx config
  file:
    src: /etc/nginx/sites-available/cuckoo_web.conf
    dest: /etc/nginx/conf.d/cuckoo_web.conf
    owner: www-data
    group: www-data
    state: link
  become: true
  notify:
    - start nginx
    - restart nginx

- name: Copy uwsgi configuration file
  copy: src=cuckoo-web.ini dest=~/ owner=cuckoo group=cuckoo mode=0755
  become_user: cuckoo
  become: true

- user:
    name: www-data
    groups: cuckoo

- name: Create uwsgi log directory
  file: path="/home/cuckoo/log/uwsgi/" state=directory
  become: true
# Debug supervisord
# - name: Copy supervisord configuration file
#   copy: src=supervisord-cuckoo-web.conf dest=/etc/supervisor/conf.d/ owner=root group=root mode=0755
#   become: true
#   notify:
#     - restart supervisord
